### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by candrews** [xbmc/visualization.starburst#2]
According to https://github.com/notspiff/visualization.starburst/blob/master/visualization.starburst/addon.xml.in, the current version is 1.1.0. Can you please tag this release?

Releases make things a lot easier for distributions (in my case, Gentoo) to package the add-on.

Thanks!

**Comment by notspiff** [comment]
Please see https://github.com/xbmc/repo-binary-addons. All those are tagged, this one and a handful of others are unfinished work.

**Comment by AlwinEsch** [comment]
The addon is reworked to use again and releases are now included
